# Fature Engineering

In [1]:
### 01. 데이터 준비
import pandas as pd
data = { "eng": ["b", "c", "a", "d"] }
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

## LabelEncoder 사용하기

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
df['라벨인코딩'] = LabelEncoder().fit_transform(df['eng'])
df

eng  라벨인코딩
0   b      1
1   c      2
2   a      0
3   d      3

## One-Hot-Encoding

In [4]:
df['라벨인코딩'].values

array([1, 2, 0, 3])

In [6]:
onehot = OneHotEncoder()
val = df['라벨인코딩'].values.reshape(-1,1) # OneHotEncoder()를 사용을 위한 적합한 값으로 변경
val

array([[1],
       [2],
       [0],
       [3]])

In [7]:
y = onehot.fit_transform( val ).toarray() # 값을 변경 후, 배열로 만들어준다.
y

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])